import type { Store, Product, Order } from "@/types";

// ================================
// DADOS MOCK - Adegas cadastradas
// ================================
export const MOCK_STORES: Store[] = [
  {
    id: "store-1",
    name: "Carlos Silva",
    email: "carlos@adegaouro.com",
    role: "store",
    storeName: "Adega Ouro Negro",
    description: "A melhor seleção de cervejas artesanais e importadas da cidade. Mais de 200 rótulos para você escolher!",
    logo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=100&h=100&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=800&h=300&fit=crop",
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: "25–40 min",
    deliveryFee: 5.90,
    minimumOrder: 30,
    neighborhood: "Vila Mariana",
    city: "São Paulo",
    isOpen: true,
    openingHours: "10:00",
    closingHours: "02:00",
    categories: ["cerveja", "whisky", "energetico", "gelo", "combo"],
    featured: true,
    phone: "(11) 99999-0001",
  },
  {
    id: "store-2",
    name: "Ana Costa",
    email: "ana@barrilhoes.com",
    role: "store",
    storeName: "Barrilhões & Cia",
    description: "Especialistas em cervejas artesanais brasileiras. Chopp gelado e combos incríveis.",
    logo: "https://images.unsplash.com/photo-1571167366136-b57e098cc3ee?w=100&h=100&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=300&fit=crop",
    rating: 4.6,
    reviewCount: 218,
    deliveryTime: "20–35 min",
    deliveryFee: 4.90,
    minimumOrder: 25,
    neighborhood: "Pinheiros",
    city: "São Paulo",
    isOpen: true,
    openingHours: "12:00",
    closingHours: "00:00",
    categories: ["cerveja", "vodka", "energetico", "gelo"],
    featured: true,
    phone: "(11) 99999-0002",
  },
  {
    id: "store-3",
    name: "Roberto Lima",
    email: "roberto@whiskyhouse.com",
    role: "store",
    storeName: "Whisky House Premium",
    description: "Importados selecionados do mundo todo. Whiskys, gins e vinhos para os mais exigentes.",
    logo: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=100&h=100&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&h=300&fit=crop",
    rating: 4.9,
    reviewCount: 156,
    deliveryTime: "30–50 min",
    deliveryFee: 8.90,
    minimumOrder: 80,
    neighborhood: "Itaim Bibi",
    city: "São Paulo",
    isOpen: true,
    openingHours: "11:00",
    closingHours: "23:00",
    categories: ["whisky", "gin", "vinho", "espumante"],
    featured: false,
    phone: "(11) 99999-0003",
  },
  {
    id: "store-4",
    name: "Fernanda Mendes",
    email: "fernanda@energyzone.com",
    role: "store",
    storeName: "Energy Zone",
    description: "Energéticos, drinks e bebidas geladas 24h. Parceiro ideal para festas!",
    logo: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=100&h=100&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1546873994-b3b5a0f97e5c?w=800&h=300&fit=crop",
    rating: 4.4,
    reviewCount: 89,
    deliveryTime: "15–25 min",
    deliveryFee: 3.90,
    minimumOrder: 20,
    neighborhood: "Consolação",
    city: "São Paulo",
    isOpen: true,
    openingHours: "00:00",
    closingHours: "23:59",
    categories: ["energetico", "refrigerante", "vodka", "gelo"],
    featured: false,
    phone: "(11) 99999-0004",
  },
  {
    id: "store-5",
    name: "Marcos Oliveira",
    email: "marcos@cantinhadobom.com",
    role: "store",
    storeName: "Cantinha do Bom Vinho",
    description: "Vinhos nacionais e importados. Harmonização perfeita para qualquer ocasião.",
    logo: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=100&h=100&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=300&fit=crop",
    rating: 4.7,
    reviewCount: 201,
    deliveryTime: "35–55 min",
    deliveryFee: 6.90,
    minimumOrder: 60,
    neighborhood: "Moema",
    city: "São Paulo",
    isOpen: false,
    openingHours: "14:00",
    closingHours: "22:00",
    categories: ["vinho", "espumante", "whisky", "gin"],
    featured: false,
    phone: "(11) 99999-0005",
  },
];

// =================================
// DADOS MOCK - Produtos das adegas
// =================================
export const MOCK_PRODUCTS: Product[] = [
  // Adega Ouro Negro (store-1)
  { id: "p1", storeId: "store-1", name: "Heineken Lata 350ml", description: "A clássica cerveja holandesa gelada e refrescante.", price: 7.90, image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&h=400&fit=crop", category: "cerveja", stock: 50, featured: true, available: true, volume: "350ml", alcoholContent: "5%" },
  { id: "p2", storeId: "store-1", name: "Pack Heineken 12 Latas", description: "Pack econômico com 12 latas de Heineken 350ml.", price: 79.90, originalPrice: 94.80, image: "https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=400&h=400&fit=crop", category: "combo", stock: 20, featured: true, available: true, volume: "4,2L" },
  { id: "p3", storeId: "store-1", name: "Jack Daniel's 750ml", description: "Tennessee Whiskey original. O clássico dos clássicos.", price: 149.90, image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=400&fit=crop", category: "whisky", stock: 15, featured: true, available: true, volume: "750ml", alcoholContent: "40%" },
  { id: "p4", storeId: "store-1", name: "Red Bull 250ml", description: "O energético original para te dar asas.", price: 12.90, image: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=400&h=400&fit=crop", category: "energetico", stock: 80, featured: false, available: true, volume: "250ml" },
  { id: "p5", storeId: "store-1", name: "Gelo em Cubo 1kg", description: "Gelo cristalino em cubo para deixar suas bebidas geladas.", price: 8.90, image: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400&h=400&fit=crop", category: "gelo", stock: 30, featured: false, available: true, volume: "1kg" },
  { id: "p6", storeId: "store-1", name: "Brahma Duplo Malte 473ml", description: "Cerveja premium com duplo processo de malte.", price: 9.90, image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400&h=400&fit=crop", category: "cerveja", stock: 60, featured: false, available: true, volume: "473ml", alcoholContent: "5%" },
  { id: "p7", storeId: "store-1", name: "Combo Festa (24 cervejas + gelo)", description: "24 latas Heineken + 2kg de gelo. Perfeito para a galera!", price: 169.90, originalPrice: 200.00, image: "https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=400&h=400&fit=crop", category: "combo", stock: 10, featured: true, available: true },
  { id: "p8", storeId: "store-1", name: "Stella Artois Long Neck 330ml", description: "A cerveja premium belga que conquistou o mundo.", price: 10.90, image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&h=400&fit=crop&random=2", category: "cerveja", stock: 40, featured: false, available: true, volume: "330ml" },

  // Barrilhões & Cia (store-2)
  { id: "p9", storeId: "store-2", name: "Colorado Appia 600ml", description: "Cerveja artesanal brasileira de malte especial.", price: 22.90, image: "https://images.unsplash.com/photo-1571167366136-b57e098cc3ee?w=400&h=400&fit=crop", category: "cerveja", stock: 25, featured: true, available: true, volume: "600ml" },
  { id: "p10", storeId: "store-2", name: "Absolut Vodka 1L", description: "Vodka sueca premium. Para os seus drinks favoritos.", price: 89.90, image: "https://images.unsplash.com/photo-1550580190-9bec5afeb935?w=400&h=400&fit=crop", category: "vodka", stock: 18, featured: true, available: true, volume: "1L", alcoholContent: "40%" },
  { id: "p11", storeId: "store-2", name: "Monster Energy 473ml", description: "O energético mais poderoso. Unleash the beast!", price: 14.90, image: "https://images.unsplash.com/photo-1546873994-b3b5a0f97e5c?w=400&h=400&fit=crop", category: "energetico", stock: 55, featured: false, available: true, volume: "473ml" },
  { id: "p12", storeId: "store-2", name: "Gelo em Barra 5kg", description: "Barra de gelo para manter tudo gelado na sua festa.", price: 19.90, image: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400&h=400&fit=crop&random=2", category: "gelo", stock: 20, featured: false, available: true, volume: "5kg" },
  { id: "p13", storeId: "store-2", name: "Skol Beats Spirit 269ml", description: "Drink pronto com sabor cítrico refrescante.", price: 13.90, image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=400&fit=crop", category: "vodka", stock: 35, featured: false, available: true, volume: "269ml" },

  // Whisky House Premium (store-3)
  { id: "p14", storeId: "store-3", name: "Johnnie Walker Black 750ml", description: "Blended Scotch Whisky de 12 anos. Sofisticado e equilibrado.", price: 189.90, image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=400&fit=crop&random=2", category: "whisky", stock: 12, featured: true, available: true, volume: "750ml", alcoholContent: "40%" },
  { id: "p15", storeId: "store-3", name: "Hendrick's Gin 750ml", description: "Gin escocês com infusão de rosa e pepino. Único!", price: 229.90, image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=400&fit=crop", category: "gin", stock: 8, featured: true, available: true, volume: "750ml", alcoholContent: "41,4%" },
  { id: "p16", storeId: "store-3", name: "Macallan 12 Anos 700ml", description: "Single Malt Scotch Whisky envelhecido em carvalho.", price: 449.90, image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=400&fit=crop&random=2", category: "whisky", stock: 5, featured: true, available: true, volume: "700ml", alcoholContent: "40%" },
  { id: "p17", storeId: "store-3", name: "Chandon Brut 750ml", description: "Espumante nacional premium. Celebre cada momento!", price: 99.90, image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop", category: "espumante", stock: 20, featured: false, available: true, volume: "750ml", alcoholContent: "12%" },

  // Energy Zone (store-4)
  { id: "p18", storeId: "store-4", name: "Kit 6x Red Bull", description: "6 latas de Red Bull 250ml. Energia para o dia todo!", price: 65.90, originalPrice: 77.40, image: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=400&h=400&fit=crop&random=2", category: "combo", stock: 30, featured: true, available: true },
  { id: "p19", storeId: "store-4", name: "Coca-Cola 2L", description: "O refrigerante original e inconfundível.", price: 11.90, image: "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400&h=400&fit=crop", category: "refrigerante", stock: 45, featured: false, available: true, volume: "2L" },
  { id: "p20", storeId: "store-4", name: "Gelo em Cubo 2kg", description: "Gelo premium cristalino para seus drinks.", price: 14.90, image: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400&h=400&fit=crop&random=3", category: "gelo", stock: 25, featured: false, available: true, volume: "2kg" },
];

// ================================
// DADOS MOCK - Pedidos iniciais
// ================================
export const MOCK_ORDERS_INITIAL: Order[] = [
  {
    id: "ord-001",
    customerId: "cust-1",
    customerName: "João Silva",
    storeId: "store-1",
    storeName: "Adega Ouro Negro",
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 2 },
      { product: MOCK_PRODUCTS[3], quantity: 1 },
    ],
    total: 28.70,
    deliveryFee: 5.90,
    status: "preparando",
    paymentMethod: "pix",
    paymentStatus: "paid",
    address: "Rua das Flores, 123",
    neighborhood: "Vila Mariana",
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 25 * 60000).toISOString(),
  },
  {
    id: "ord-002",
    customerId: "cust-2",
    customerName: "Maria Santos",
    storeId: "store-1",
    storeName: "Adega Ouro Negro",
    items: [
      { product: MOCK_PRODUCTS[1], quantity: 1 },
      { product: MOCK_PRODUCTS[4], quantity: 2 },
    ],
    total: 97.70,
    deliveryFee: 5.90,
    status: "aguardando",
    paymentMethod: "pix",
    paymentStatus: "pending",
    address: "Av. Paulista, 456",
    neighborhood: "Bela Vista",
    createdAt: new Date(Date.now() - 3 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 40 * 60000).toISOString(),
  },
];

// Categorias com labels e emojis
export const CATEGORIES = [
  { id: "cerveja", label: "Cerveja", emoji: "🍺" },
  { id: "whisky", label: "Whisky", emoji: "🥃" },
  { id: "vodka", label: "Vodka", emoji: "🍸" },
  { id: "vinho", label: "Vinho", emoji: "🍷" },
  { id: "energetico", label: "Energético", emoji: "⚡" },
  { id: "gelo", label: "Gelo", emoji: "🧊" },
  { id: "combo", label: "Combos", emoji: "🎉" },
  { id: "refrigerante", label: "Refrigerante", emoji: "🥤" },
  { id: "espumante", label: "Espumante", emoji: "🥂" },
  { id: "gin", label: "Gin", emoji: "🌿" },
];

export const ORDER_STATUS_LABELS: Record<string, string> = {
  aguardando: "Aguardando confirmação",
  aceito: "Pedido aceito",
  recusado: "Pedido recusado",
  preparando: "Preparando pedido",
  coletado: "Coletado pelo entregador",
  em_rota: "Saiu para entrega",
  entregue: "Entregue!",
};

export const ORDER_STATUS_COLORS: Record<string, string> = {
  aguardando: "text-brand-yellow bg-brand-yellow/10 border-brand-yellow/30",
  aceito: "text-brand-green bg-brand-green/10 border-brand-green/30",
  recusado: "text-brand-red bg-brand-red/10 border-brand-red/30",
  preparando: "text-blue-400 bg-blue-400/10 border-blue-400/30",
  coletado: "text-purple-400 bg-purple-400/10 border-purple-400/30",
  em_rota: "text-orange-400 bg-orange-400/10 border-orange-400/30",
  entregue: "text-brand-green bg-brand-green/10 border-brand-green/30",
};
